/**
 * Question bank registry.
 * Each bank describes WHERE questions come from and HOW they behave.
 * Actual question content lives in separate JSON files (added in a later phase).
 */
export const QUESTION_BANKS = {
  // ── Math ──────────────────────────────────────────────────────────────────
  'math-single-digit-multiplication': {
    id: 'math-single-digit-multiplication',
    curriculum: 'math',
    topic: 'multiplication',
    difficulty: 1,
    gradeRange: [2, 3],
    questionTypes: ['multiple-choice', 'fill-in-blank'],
    sourceFile: 'data/questions/math/single-digit-multiplication.json',
    tags: ['times-tables', 'single-digit'],
  },
  'math-double-digit-multiplication': {
    id: 'math-double-digit-multiplication',
    curriculum: 'math',
    topic: 'multiplication',
    difficulty: 2,
    gradeRange: [3, 4],
    questionTypes: ['multiple-choice', 'fill-in-blank'],
    sourceFile: 'data/questions/math/double-digit-multiplication.json',
    tags: ['two-digit', 'multiplication'],
  },
  'math-triple-digit-multiplication': {
    id: 'math-triple-digit-multiplication',
    curriculum: 'math',
    topic: 'multiplication',
    difficulty: 3,
    gradeRange: [4, 5],
    questionTypes: ['multiple-choice', 'fill-in-blank', 'word-problem'],
    sourceFile: 'data/questions/math/triple-digit-multiplication.json',
    tags: ['three-digit', 'multiplication'],
  },
  'math-fractions-basics': {
    id: 'math-fractions-basics',
    curriculum: 'math',
    topic: 'fractions',
    difficulty: 2,
    gradeRange: [3, 4],
    questionTypes: ['multiple-choice', 'visual-match'],
    sourceFile: 'data/questions/math/fractions-basics.json',
    tags: ['fractions', 'numerator', 'denominator'],
  },

  // ── Science ───────────────────────────────────────────────────────────────
  'science-solar-system': {
    id: 'science-solar-system',
    curriculum: 'science',
    topic: 'astronomy',
    difficulty: 1,
    gradeRange: [2, 4],
    questionTypes: ['multiple-choice', 'image-label'],
    sourceFile: 'data/questions/science/solar-system.json',
    tags: ['planets', 'space'],
  },
  'science-states-of-matter': {
    id: 'science-states-of-matter',
    curriculum: 'science',
    topic: 'physics',
    difficulty: 2,
    gradeRange: [3, 5],
    questionTypes: ['multiple-choice', 'sorting'],
    sourceFile: 'data/questions/science/states-of-matter.json',
    tags: ['solid', 'liquid', 'gas'],
  },
  'science-ecosystems': {
    id: 'science-ecosystems',
    curriculum: 'science',
    topic: 'biology',
    difficulty: 2,
    gradeRange: [4, 6],
    questionTypes: ['multiple-choice', 'food-chain'],
    sourceFile: 'data/questions/science/ecosystems.json',
    tags: ['habitats', 'food-chain'],
  },

  // ── Reading ───────────────────────────────────────────────────────────────
  'reading-phonics-basics': {
    id: 'reading-phonics-basics',
    curriculum: 'reading',
    topic: 'phonics',
    difficulty: 1,
    gradeRange: ['K', 2],
    questionTypes: ['sound-match', 'multiple-choice'],
    sourceFile: 'data/questions/reading/phonics-basics.json',
    tags: ['phonics', 'letter-sounds'],
  },
  'reading-comprehension-short': {
    id: 'reading-comprehension-short',
    curriculum: 'reading',
    topic: 'comprehension',
    difficulty: 2,
    gradeRange: [2, 4],
    questionTypes: ['passage-then-questions'],
    sourceFile: 'data/questions/reading/comprehension-short.json',
    tags: ['reading-passage', 'main-idea'],
  },
  'reading-vocabulary-context': {
    id: 'reading-vocabulary-context',
    curriculum: 'reading',
    topic: 'vocabulary',
    difficulty: 3,
    gradeRange: [4, 6],
    questionTypes: ['context-clue', 'multiple-choice'],
    sourceFile: 'data/questions/reading/vocabulary-context.json',
    tags: ['vocabulary', 'context-clues'],
  },

  // ── History ───────────────────────────────────────────────────────────────
  'history-ancient-egypt': {
    id: 'history-ancient-egypt',
    curriculum: 'history',
    topic: 'ancient-civilizations',
    difficulty: 2,
    gradeRange: [3, 5],
    questionTypes: ['multiple-choice', 'timeline-order'],
    sourceFile: 'data/questions/history/ancient-egypt.json',
    tags: ['egypt', 'pharaohs', 'pyramids'],
  },
  'history-american-revolution': {
    id: 'history-american-revolution',
    curriculum: 'history',
    topic: 'american-history',
    difficulty: 3,
    gradeRange: [4, 6],
    questionTypes: ['multiple-choice', 'cause-and-effect'],
    sourceFile: 'data/questions/history/american-revolution.json',
    tags: ['revolution', 'founding-fathers'],
  },
  'history-world-war-ii-basics': {
    id: 'history-world-war-ii-basics',
    curriculum: 'history',
    topic: 'world-history',
    difficulty: 4,
    gradeRange: [6, 8],
    questionTypes: ['multiple-choice', 'map-label'],
    sourceFile: 'data/questions/history/world-war-ii-basics.json',
    tags: ['wwii', 'timeline'],
  },
};
