/**
 * Pop-Art / Neubrutalism theme palettes.
 * Flat, bold fills — no soft gradients or blurry shadows.
 */
export const BOARD_THEMES = {
  forest: {
    label: 'Enchanted Forest',
    page: 'bg-lime-300',
    board: 'bg-emerald-200',
    track: 'bg-lime-100',
    tile: 'bg-green-400 text-black',
    quiz: 'bg-yellow-300 text-black',
    boss: 'bg-red-500 text-white',
    pawn: 'bg-sky-400 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#4ade80',
    diceBtn: 'bg-white text-black hover:bg-lime-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  volcano: {
    label: 'Molten Volcano',
    page: 'bg-orange-200',
    board: 'bg-amber-100',
    track: 'bg-orange-100',
    tile: 'bg-orange-400 text-black',
    quiz: 'bg-yellow-300 text-black',
    boss: 'bg-purple-700 text-white',
    pawn: 'bg-cyan-400 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#fb923c',
    diceBtn: 'bg-white text-black hover:bg-orange-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  ocean: {
    label: 'Deep Ocean',
    page: 'bg-sky-200',
    board: 'bg-cyan-100',
    track: 'bg-sky-100',
    tile: 'bg-cyan-400 text-black',
    quiz: 'bg-yellow-300 text-black',
    boss: 'bg-indigo-600 text-white',
    pawn: 'bg-yellow-300 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#22d3ee',
    diceBtn: 'bg-white text-black hover:bg-sky-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  library: {
    label: 'Grand Library',
    page: 'bg-amber-200',
    board: 'bg-amber-100',
    track: 'bg-yellow-50',
    tile: 'bg-amber-400 text-black',
    quiz: 'bg-orange-300 text-black',
    boss: 'bg-stone-700 text-white',
    pawn: 'bg-rose-400 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#fbbf24',
    diceBtn: 'bg-white text-black hover:bg-amber-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  castle: {
    label: 'Royal Castle',
    page: 'bg-violet-200',
    board: 'bg-purple-100',
    track: 'bg-violet-100',
    tile: 'bg-violet-400 text-black',
    quiz: 'bg-fuchsia-300 text-black',
    boss: 'bg-yellow-400 text-black',
    pawn: 'bg-emerald-400 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#a78bfa',
    diceBtn: 'bg-white text-black hover:bg-violet-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  laboratory: {
    label: 'Mad Scientist Lab',
    page: 'bg-fuchsia-200',
    board: 'bg-purple-100',
    track: 'bg-fuchsia-100',
    tile: 'bg-lime-400 text-black',
    quiz: 'bg-yellow-300 text-black',
    boss: 'bg-purple-600 text-white',
    pawn: 'bg-orange-400 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#e879f9',
    diceBtn: 'bg-white text-black hover:bg-fuchsia-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  desert: {
    label: 'Ancient Desert',
    page: 'bg-yellow-200',
    board: 'bg-amber-100',
    track: 'bg-yellow-100',
    tile: 'bg-yellow-400 text-black',
    quiz: 'bg-orange-400 text-black',
    boss: 'bg-red-600 text-white',
    pawn: 'bg-blue-500 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#facc15',
    diceBtn: 'bg-white text-black hover:bg-yellow-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
  space: {
    label: 'Outer Space',
    page: 'bg-indigo-200',
    board: 'bg-violet-100',
    track: 'bg-indigo-100',
    tile: 'bg-indigo-400 text-white',
    quiz: 'bg-pink-300 text-black',
    boss: 'bg-fuchsia-600 text-white',
    pawn: 'bg-yellow-300 border-black',
    title: 'text-black',
    subtitle: 'text-black/70',
    accent: '#818cf8',
    diceBtn: 'bg-white text-black hover:bg-indigo-50',
    diceBtnDisabled: 'bg-stone-200 text-stone-400',
  },
};

export function getBoardTheme(themeId) {
  return BOARD_THEMES[themeId] ?? BOARD_THEMES.forest;
}
